Artifactory:
  server: <your server> #change to your servername
  intName: artifactory_integration
  devRepo: workshop-docker-local
  prodRepo: workshop-docker-prod-local
GitHub:
  path: <github username>/aws-eks-workshop #change to your github username
  gitProvider: github_integration
AWS:
  intName: aws_integration
  eks: eks_integration
  region: us-west-2
app:
  dockerImageName: <your server>/workshop-docker/eks-workshop-app #change to your servername
  dockerFileLocation: workshop-app
  buildName: eks-workshop-app
