resources:
  - name: gitRepo
    type: GitRepo
    configuration:
      path: jfrogtraining/aws-eks-workshop
      gitProvider: jefferyfryGithub
      branches:
        include: master
  - name: workshop_build_info
    type: Buildinfo
    configuration:
      sourceArtifactory: PartnershipArtifactory
      buildName: workshop_build
      buildNumber: ${run_number}
  - name: promoted_workshop_build_info
    type: Buildinfo
    configuration:
      sourceArtifactory: PartnershipArtifactory
      buildName: workshop_build
      buildNumber: ${run_number}

pipelines:
  - name: workshop_app_build
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: docker_build
          dockerFileLocation: workshop-app
          dockerFileName: Dockerfile
          dockerImageName: partnership-workshop-docker.jfrog.io/workshop-app
          dockerImageTag: ${run_number}
          inputResources:
            - name: gitRepo
          integrations:
            - name: PartnershipArtifactory
        execution:
          onSuccess:
            - echo "Congrats The Docker image was built!"
      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: docker_build
          targetRepository: workshop-docker-local
          autoPublishBuildInfo: true
          forceXrayScan: true
          integrations:
            - name:  PartnershipArtifactory
          inputSteps:
            - name: docker_build
          outputResources:
            - name: workshop_build_info
      - name: docker_promote
        type: PromoteBuild
        configuration:
          targetRepository:      workshop-docker-prod-local
          includeDependencies:   true
          status:                Passed
          comment:               Artifact passed Xray Scan
          copy:                  true
          inputSteps:
            - name: docker_push
          inputResources:
            - name:    workshop_build_info
              trigger: true
          outputResources:
            - name: promoted_workshop_build_info
      - name: eks_deploy
        type: Bash
        configuration:
          integrations:
            - name: jeffAws
            - name: jeffEksK8s
          inputResources:
            - name: gitRepo
          inputSteps:
            - name: docker_promote
        execution:
          onExecute:
            - cd $res_gitRepo_resourcePath
            - pwd
            - ls
            - kubectl create namespace aws-eks-workshop
            - sed "s|imageName|partnership-workshop-docker.jfrog.io/workshop-app${run_number}|g" workshop-app/deployment.yaml > my-deployment.yaml
            - cat my-deployment.yaml
            - kubectl apply -f my-deployment.yaml --namespace aws-eks-workshop
