resources:
  - name: gitRepo
    type: GitRepo
    configuration:
      path: jfrogtraining/aws-eks-workshop
      gitProvider: jefferyfryGithub
      branches:
        include: master
  - name: workshop_build_info
    type: Buildinfo
    configuration:
      sourceArtifactory: PartnershipArtifactory
      buildName: workshop_build
      buildNumber: ${run_number}
  - name: promoted_workshop_build_info
    type: Buildinfo
    configuration:
      sourceArtifactory: PartnershipArtifactory
      buildName: workshop_build
      buildNumber: ${run_number}

pipelines:
  - name: workshop_app_build
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: docker_build
          dockerFileLocation: workshop-app
          dockerFileName: Dockerfile
          dockerImageName: partnership-workshop-docker.jfrog.io/workshop-app
          dockerImageTag: ${run_number}
          inputResources:
            - name: gitRepo
          integrations:
            - name: PartnershipArtifactory
        execution:
          onSuccess:
            - echo "Congrats The Docker image was built!"
      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: docker_build
          targetRepository: partnership-workshop-docker.jfrog.io/workshop-docker
          autoPublishBuildInfo: true
          forceXrayScan: true
          integrations:
            - name:  PartnershipArtifactory
          inputSteps:
            - name: docker_build
          outputResources:
            - name: workshop_build_info
      - name: docker_promote
        type: PromoteBuild
        configuration:
          targetRepository:      partnership-workshop-docker.jfrog.io/workshop-docker-prod-local
          includeDependencies:   true
          status:                Passed
          comment:               Artifact passed Xray Scan
          copy:                  false
          inputResources:
            - name:    workshop_build_info
              trigger: false
          outputResources:
            - name: promoted_workshop_build_info
